export default {
  // Mocking api fetch call
  getIconList: () => Promise.resolve([
    'help',
    'face',
    'adb',
    'sentiment_satisfied_alt',
    'fitness_center',
    'cake',
    'beach_access',
    'security',
    'thumb_up',
    'visibility',
    'pregnant_woman',
    'bug_report',
    'build',
    'favorite',
    'explore',
    'language',
    'lock',
    'opacity',
    'motorcycle',
    'offline_bolt',
    'redeem',
    'rowing',
    'star',
    'shopping_cart',
    'store',
    'person',
  ]),
};
